---
title: "Excercise6"
author: "Dingyi Lai"
date: "1/5/2021"
output: html_document
---


```{r}
myPermuCI <- function(nsim,nperm,n1,n2,v1,v2,delta, Distribution){
  PermCI=c()
  N <- n1+n2
  #-------Data Generation------#
  vvec <- sqrt(c(rep(v1,n1),rep(v2,n2)))
  
  if(Distribution == "Normal"){
    x1 = matrix(rnorm(n1*nsim,delta)*sqrt(v1),ncol = nsim)
    x2 = matrix(rnorm(n2*nsim)*sqrt(v2),ncol = nsim)
  }
  
  if(Distribution == "Exponential"){
    x1 = matrix((rexp(n = n1*nsim)-1+delta)*sqrt(v1),ncol=nsim)
    x2 = matrix((rexp(n = n2*nsim)-1)*sqrt(v2),ncol=nsim)
  }
  
  xy = rbind(x1,x2)
  x12 = x1^2
  x22 = x2^2
  mx = colMeans(x1)
  my = colMeans(x2)
  vx = (colSums(x12)-n1*mx^2)/(n1-1)
  vy = (colSums(x22)-n2*my^2)/(n2-1)
  df = (vx/n1+vy/n2)^2/(vx^2/(n1^2*(n1-1))+vy^2/(n2^2*(n2-1)))
  T.L <- mx-my-qt(0.975,df)*sqrt(vx/n1+vy/n2)
  T.U <- mx-my+qt(0.975,df)*sqrt(vx/n1+vy/n2)
  
  #--------------Permutation matrices------------------#
  P <- t(apply(matrix(1:N, nrow = nperm,ncol = N,byrow = TRUE), 1, sample))
  
  #---------Helping Variables for Permutation Distribution-------#
  i1 <- c(rep(1/n1,n1),rep(0,n2))
  i2 <- c(rep(0,n1),rep(1/n2,n2))
  i3 <- c(rep(1/(n1*(n1-1)),n1),rep(0,n2))
  i4 <- c(rep(0,n1),rep(1/(n2*(n2-1)),n2))
  Im1 <- matrix(i1[P],nrow = nperm,ncol = N)
  Im2 <- matrix(i2[P],nrow = nperm,ncol = N)
  Iv1 <- matrix(i3[P],nrow = nperm,ncol = N)
  Iv2 <- matrix(i4[P],nrow = nperm,ncol = N)
  
  #--------------Begin of Simulation------------------#
  for (i in 1:nsim) {
    X <- xy[,i]
    
    #--------------Permutation---------------#
    mxP <- Im1 %*% X
    myP <- Im2 %*% X
    vxP <- Iv1 %*% X^2 - n1/(n1*(n1-1))*mxP^2
    vyP <- Iv2 %*% X^2 - n2/(n2*(n2-1))*myP^2
    TP <- (mxP - myP)/sqrt(vxP + vyP)
    c1 <- quantile(TP,0.025)
    c2 <- quantile(TP,0.975)
    lower <- mx[i]-my[i]-c2*sqrt(vx[i]/n1+vy[i]/n2)
    upper <- mx[i]-my[i]-c1*sqrt(vx[i]/n1+vy[i]/n2)
    PermCI[i] <- (lower<delta & upper>delta)
    #--------------End of Simulation------------------#
  }
  Result <- data.frame(nsim = nsim, nperm = nperm, delta = delta, n1 = n1, n2 = n2, v1 = v1, v2 = v2, SW=mean(T.L<delta & T.U>delta),PermCI = mean(PermCI), Distribution = Distribution)
  write.table(Result, row.names = FALSE, col.names = FALSE, quote = FALSE, append = TRUE)
  return(Result)
  #--------------End of Function------------------#
}
set.seed(1)
Dist <- c("Normal","Exponential")
delta <- seq(0, 2, by = 0.1)
n1 <- c(10,20,30)
n2 <- c(10,20,30)
nsim <- 10000
nperm <- 10000

for(h in 1:length(n1)){
  for(hh in 1:length(n2)){
    for(hhh in 1:length(delta)){
      for(hhhh in 1:length(Dist)){
        myPermuCI(nsim,nperm,n1[h],n2[hh],1,1,delta[hhh],Dist[hhhh])
      }
    }
  }
}
```




```{r}
rm(list = ls()) 
library(ggplot2)
# create data
x <- c(8,7,6,7,6,5,6,5,4,5,4,3,4,3,2,3,2,1,0.5,0.1)
dat1 <- data.frame(x1 = 1:length(x), x2 = x)
dat2 <- data.frame(x1 = 1:length(x), x2 = -x)
dat1$xvar <- dat2$xvar <- NA
dat1$yvar <- dat2$yvar <- NA
dat1$siz <- dat2$siz <- NA
dat1$col <- dat2$col <- NA
dec_threshold = -0.5
set.seed(2512)
for (row in 1:nrow(dat1)){
  if (rnorm(1) > dec_threshold){
    dat1$xvar[row] <- row
    dat1$yvar[row] <- sample(1:dat1$x2[row]-1,1)
    dat1$siz[row] <- runif(1,0.5,1.5)
    dat1$col[row] <- sample(1:5, 1)
  }
  if (rnorm(1) > dec_threshold){
    dat2$xvar[row] <- row
    dat2$yvar[row] <- sample(1:dat2$x2[row],1)
    dat2$siz[row] <- runif(1,0.5,1.5)
    dat2$col[row] <- sample(1:5, 1)
  }
}
# plot the christmas tree
ggplot() + geom_bar(data = dat1, aes(x=x1, y=x2),stat = "identity", fill = '#31a354') + geom_bar(data = dat2, aes(x=x1, y=x2),stat = "identity", fill = '#31a354') + geom_point(data = dat1,aes(x = xvar, y = yvar, size = siz, colour = as.factor(col)) ) + geom_point(data = dat2,aes(x = xvar, y = yvar, size = siz, colour = as.factor(col)) ) + coord_flip() + theme_minimal()+ theme(legend.position="none", axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.title.y=element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank()) +ggtitle('We wish you a Merry Christmas')
```

